version: 2.0

jobs:
  build:
    docker:
      - image: maven:3.3-jdk-8
    steps:
      - checkout
      - run:
          name: "Package a build"
          command: mvn -e clean package
      - persist_to_workspace:
          root: ./
          paths:
            - target/release/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_TAG
            ZIP_FILE=ItemsExtractor-${VERSION}.zip
            cd workspace/target/release/ && zip -r ${ZIP_FILE} ItemsExtractor-${VERSION}/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "Items Extractor ${VERSION}" -recreate -prerelease ${VERSION} ${ZIP_FILE}

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
